version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sftp-file-handler"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n7mvj5hdydn"
s3_prefix = "sftp-file-handler"
region = "us-east-1"
profile = "aws-support"
capabilities = "CAPABILITY_IAM"
image_repositories = []
